# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'getoptlong'
opts = GetoptLong.new(
	[ '--registration-token', GetoptLong::OPTIONAL_ARGUMENT ]
)
REGISTRATION_TOKEN=''

opts.each do |opt, arg|
	case opt
		when '--registration-token'
			REGISTRATION_TOKEN=arg
	end
end


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "ci-runner"
  config.vm.network :private_network, ip: "192.168.33.45"
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

  config.vm.provision "shell", inline: $script

end

$script = <<SCRIPT
	sudo curl -L --output /usr/local/bin/gitlab-runner \
	"https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
	 sudo chmod +x /usr/local/bin/gitlab-runner
	sudo useradd --comment 'GitLab Runner' \
	--create-home gitlab-runner --shell /bin/bash
	sudo gitlab-runner install \
	--user=gitlab-runner \
	--working-directory=/home/gitlab-runner
	sudo gitlab-runner start
	sudo gitlab-runner register \
	--non-interactive \
	--url "http://192.168.33.44/" \
	--registration-token "#{REGISTRATION_TOKEN}" \
	--executor "shell" \
	--description "shell-runner" \
	--maintenance-note "Free-form maintainer notes about this runner" \
	--tag-list "shell,aws" \
	--run-untagged="true" \
	--locked="false" \
	--access-level="not_protected"
SCRIPT
